[package]
name = "StegHtml"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.4"
regex = "1.11.1"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "StegHtml"
path = "src/StegHtml.rs"
